### ISSUE TITLE
Travis CI build #24 is broken

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-language-service#24]
[Travis CI build #24](https://travis-ci.org/rcjsuen/dockerfile-language-service/builds/350269565) is currently broken. The example won't build because of the API changes introduced by 3928ff57c9e00e55ce639114f64dc574551b3701 for #23.
```
$ npm run build

> @rcjsuen/dockerfile-language-service-example@0.0.1 build /home/travis/build/rcjsuen/dockerfile-language-service/example
> npm run compile && webpack && npm run copy


> @rcjsuen/dockerfile-language-service-example@0.0.1 compile /home/travis/build/rcjsuen/dockerfile-language-service/example

> tsc
src/client.ts(77,23): error TS2554: Expected 2 arguments, but got 3.
```
