### ISSUE TITLE
Travis CI build #19 is broken

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-language-service#19]
Travis CI [build #19](https://travis-ci.org/rcjsuen/dockerfile-language-service/jobs/350014932) is currently broken.

```
$ npm run build

> @rcjsuen/dockerfile-language-service-example@0.0.1 build /home/travis/build/rcjsuen/dockerfile-language-service/example
> npm run compile && webpack && npm run copy


> @rcjsuen/dockerfile-language-service-example@0.0.1 compile /home/travis/build/rcjsuen/dockerfile-language-service/example
> tsc

src/client.ts(88,67): error TS2345: Argument of type 'CompletionItem' is not assignable to parameter of type 'CompletionItem'.
  Types of property 'kind' are incompatible.
    Type '2 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 1 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 2...' is not assignable to type '2 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 1 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | undefined'.
      Type '19' is not assignable to type '2 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 1 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | undefined'.
```

**Comment by rcjsuen** [comment]
Here are the relevant lines of code:

https://github.com/rcjsuen/dockerfile-language-service/blob/cd32562f212692dd5731eefd36c11db799363fbb/example/src/client.ts#L72-L90

**Comment by rcjsuen** [comment]
Builds are green again! This is likely due to the version bump to `vscode-languageserver-types` introduced in 553117f107c559c2c36f9a1528b53b4e4f72ad1a as well as the new `package-lock.json` files that were added in 1b2cae2eb2b384c2bf11222c74bfad50acfc3144 to ensure that the same dependency tree would be used in both local development and in Travis CI.
