### ISSUE TITLE
Travis build #60 is broken

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-language-service#44]
Looks like [build #60](https://travis-ci.org/rcjsuen/dockerfile-language-service/builds/472634284) is broken because of a compiler error introduced by 54ce0e277397c2dd92e6819c71cf7a166d8ace16 when fixing #43.
```
$ npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> dockerfile-language-service@0.0.6 prepublish /home/travis/build/rcjsuen/dockerfile-language-service
> tsc -p ./src

src/dockerFolding.ts(24,72): error TS2339: Property 'MAX_SAFE_INTEGER' does not exist on type 'NumberConstructor'.
```

**Comment by rcjsuen** [comment]
Fixed by c1424f4a9d1c3910bbb962b8222a7227c952425c.
