### ISSUE TITLE
Travis CI build #15 is broken

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-language-service#16]
I forgot to update the example so [build #15](https://travis-ci.org/rcjsuen/dockerfile-language-service/builds/347695246) got broken by d462327d3245aad5ef5deb307789490454b9b167.

```
> @rcjsuen/dockerfile-language-service-example@0.0.1 compile /home/travis/build/rcjsuen/dockerfile-language-service/example
> tsc

src/client.ts(101,33): error TS2554: Expected 2 arguments, but got 3.
```
